---
title: "Covid Studies"
output: html_notebook
---

# 1st Analysis - Population & Infection Rate
```{r}
library(tidyverse)
pop.IR <- current_by_state %>%
  select(state, population, IR = metrics.infectionRate) %>%
  filter(state != "MP")
ggplot(pop.IR, aes(population, IR)) +
   geom_point() +
   scale_x_continuous(name = "Population in millions (log10 scale)", trans = "log10", breaks = c(1e+06, 3e+06, 1e+07, 3e+07), labels = c("1", "3", "10", "30")) +
   scale_y_continuous(name = "Infection Rate (IR)") +
   geom_smooth(method = "loess", se = FALSE) +
   geom_smooth(method = "lm", se = FALSE, color = "green") +
   geom_hline(yintercept = 1, color = "red") +
   annotate("text", label = "As of 12/4/21", x = 3e+07, y = 1.4, size = 4, color = "grey60") +
   annotate("text", label = "(Excludes N. Mariana Is. / IR = 1.69)", x = 2e+07, y = 0.75, size = 3, color = "grey60") +
  theme_classic()
```

---  
  
# 2nd Analysis - Population & Case Rate
```{r}
library(tidyverse)
library(ggpmisc)
pop.CR <- current_by_state %>%
  select(state, population, actuals.cases) %>%
  mutate(CR = actuals.cases / population)
# boxplot of CR
CR_temp <- arrange(pop.CR, desc(CR))
CR_temq <- CR_temp[-(1:50),c(1, 4)]
ggplot(pop.CR, aes(CR)) +
   geom_boxplot() +
   coord_flip() + 
   annotate(geom = "table", label = list(CR_temq), y = 0.4, x = 0) +
   theme(axis.text.x = element_blank(), axis.ticks.x = element_blank()) 
# scatterplot of population & CR
pop.CR <- filter(pop.CR, state != "MP")
ggplot(pop.CR, aes(population, CR)) +
   geom_point() +
   scale_x_continuous(name = "Population in millions (log10 scale)", trans = "log10", breaks = c(1e+06, 3e+06, 1e+07, 3e+07), labels = c("1", "3", "10", "30")) +
   scale_y_continuous(name = "Case Rate (CR)", limits = c(0, 0.3)) +
   geom_smooth(method = "loess", se = FALSE) +
   geom_smooth(method = "lm", se = FALSE, color = "green") +
   annotate("text", label = "As of 12/4/21", x = 3e+07, y = 0.3, size = 4, color = "grey60") +
   annotate("text", label = "(Excludes N. Mariana Is. / pop = 54k)", x = 2e+07, y = 0, size = 3, color = "grey60") +
   theme_classic()
```
